name: Query issue report
description: Report a query issue to help improve the project
title: 'Query issue: '
labels: 
  - query

body:
  - type: markdown
    attributes:
      value: |
        # Report an issue with a BloodHound query
        Use this issue/form to report any issues with a query saved in the repository

  - type: markdown
    attributes:
      value: |
        ## Query details
        
  - type: input
    id: guid
    attributes:
      label: Query GUID
      description: The query unique's identifier
    validations:
      required: true

  - type: textarea
    id: query_body
    attributes:
      label: Query content
      description: |
        The BloodHound query content
        ```bash
        MATCH p = (s:Computer)-[:DCFor]->(:Domain)
        WHERE s.strongcertificatebindingenforcementraw = 0 OR s.strongcertificatebindingenforcementraw = 1
        RETURN p
        LIMIT 1000
        ```
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: Issue description
      description: |
        Describe the issue faced when using the query
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## BloodHound context

  - type: input
    id: bloodhound_version
    attributes:
      label: BloodHound version
      description: The version of BloodHound used when trying to run the query
      placeholder: BloodHound CE 7.0
    validations:
      required: true

  - type: input
    id: bloodhound_db
    attributes:
      label: BloodHound DB
      description: "The database used for BloodHound (hint: CE uses Neo4j by default, while BHE is always Postgres)"
      placeholder: e.g. Neo4j or Postgres
    validations:
      required: true
