name: Query syntax validation
on:
  pull_request:
    branches: [ 'main' ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test queries with pytest
      run: |
        pytest tests/test_cypher_syntax.py

    - name: Add test report to summary
      run: cat test-report.md >> $GITHUB_STEP_SUMMARY

    - name: Upload test report 
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test-report.md
