name: Query syntax validation
on:
  pull_request:
    branches: [ 'main' ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test queries with pytest
      run: |
        pytest tests/test_cypher_syntax.py

    - name: Add test report to summary
      run: cat test-report.md >> $GITHUB_STEP_SUMMARY

    - name: Upload test report 
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test-report.md

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Convert queries into single json
        run: |
          python utilities/python/convert.py ./queries ./Queries.json

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit if changed
        run: |
          git add ./Queries.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update combined queries"
            git push
          fi
